### PR TITLE
Feature/tweaks

### PR DESCRIPTION
**Pull request by matyj**

### CODE REVIEW

**Review by lkincel — APPROVED** [review]

**Review by sewerynzalupka — APPROVED** [review]
looks good, does it need any adjustments on iOS native side?

**Comment by matyj** [comment]
ofc, it should be implemented exactly the same way ;)

**Comment by sewerynzalupka** [comment]
Unfortunately the iOS implementation does not work yet

**Comment by sewerynzalupka** [comment]
Fixed issues with iOS implementation
Caveats:
tweaks MUST be defined at compile time on iOS
`createBooleanTweak` is basically a stub implementation on iOS that does nothing and resolves with `nil`
to 'create' a tweak on iOS you have to call for it's value using `MPTweakValue` macro, like this:
```objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
   ...
   MPTweakValue(@"ENABLE_REGISTRATION", YES);
   return YES;
}
```

**Pull request merged**
